spring:
  cloud:
    openfeign:
      client:
        config:
          kakao-oidc-key-client:
            url: https://kauth.kakao.com
          apple-oidc-key-client:
            url: https://appleid.apple.com

  profiles:
    group:
      local-env:
        - local
      dev-env:
        - dev
      prod-env:
        - prod
    include:
      - jwt
      - secret

springdoc:
  packages-to-scan: com.guttery.madii
  swagger-ui.path: /api-docs
  swagger-ui.tags-sorter: alpha
  swagger-ui.operations-sorter: alpha
  api-docs.path: /api-docs/json
  api-docs.groups.enabled: true
  cache.disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

server:
  servlet:
    encoding:
      force-response: true
