/*
-- Query: select *
from t_album
where 1=1
LIMIT 0, 300

-- Date: 2024-03-17 22:58
*/
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (1,now(),now(),1,7,'0','0','1','낭만 가득 소확행 앨범입니다','낭만 가득 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (2,now(),now(),1,8,'0','0','1','힐링이 필요한 나를 위한 앨범입니다','힐링이 필요한 나를 위해!',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (3,now(),now(),1,9,'0','0','1','오직 나만을 위한 소확행 선물 앨범입니다','오직 나만을 위한 소확행 선물',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (4,now(),now(),1,10,'0','0','1','영상 시청을 통한 힐링 앨범입니다','영상 시청을 통한 힐링',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (5,now(),now(),1,11,'0','0','1','위로가 필요한 날 앨범입니다','위로가 필요한 날',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (6,now(),now(),1,12,'0','0','1','가족과 함께 보내는 따뜻한 소확행 앨범입니다','가족과 함께 보내는 따뜻한 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (7,now(),now(),2,2,'0','0','1','다른 사람과 함께 행복해지는 소확행 앨범입니다','다른 사람과 함께 행복해지는 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (8,now(),now(),2,3,'0','0','1','귀여움으로 가득찬 소확행 앨범입니다','귀여움으로 가득찬 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (9,now(),now(),2,4,'0','0','1','추억 여행으로 행복 느끼기 앨범입니다','추억 여행으로 행복 느끼기',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (10,now(),now(),2,1,'0','0','1','여유로운 일요일을 즐길 수 있는 행복 모음 앨범입니다','여유로운 일요일을 즐길 수 있는 행복 모음',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (11,now(),now(),2,5,'0','0','1','나만의 향기로 가득찰 오늘 앨범입니다','나만의 향기로 가득찰 오늘',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (12,now(),now(),2,6,'0','0','1','뿌듯한 하루를 위한 소확행 앨범입니다','뿌듯한 하루를 위한 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (13,now(),now(),3,19,'0','0','1','집에서 실천 가능한 소확행 앨범입니다','집에서 실천 가능한 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (14,now(),now(),3,20,'0','0','1','에너제틱한 하루를 위한 소확행 앨범입니다','에너제틱한 하루를 위한 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (15,now(),now(),3,21,'0','0','1','여행에서 느끼는 소확행 앨범입니다','여행에서 느끼는 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (16,now(),now(),3,22,'0','0','1','새로움으로 가득찬 소확행 앨범입니다','새로움으로 가득찬 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (17,now(),now(),3,23,'0','0','1','따끈한 겨울을 위한 소확행 앨범입니다','따끈한 겨울을 위한 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (18,now(),now(),3,24,'0','0','1','비 오는 날 소확행 앨범입니다','비 오는 날 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (19,now(),now(),4,13,'0','0','1','우리 동네에서 할 수 있는 소확행 앨범입니다','우리 동네에서 할 수 있는 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (20,now(),now(),4,14,'0','0','1','만원 미만으로 실천할 수 있는 소확행 앨범입니다','만원 미만으로 실천할 수 있는 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (21,now(),now(),4,15,'0','0','1','상상 속으로 떠나는 여행 앨범입니다','상상 속으로 떠나는 여행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (22,now(),now(),4,16,'0','0','1','빵순이의 빵만 먹는 소확행 앨범입니다','빵순이의 빵만 먹는 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (23,now(),now(),4,17,'0','0','1','봄 향기 가득한 소확행 앨범입니다','봄 향기 가득한 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (24,now(),now(),4,18,'0','0','1','에너지 뿜뿜 올라가는 소확행 앨범입니다','에너지 뿜뿜 올라가는 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (25,now(),now(),1,13,'0','0','1','겨울에도 따뜻함을 느낄 수 있는 소확행 앨범입니다','겨울에도 따뜻함을 느낄 수 있는 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (26,now(),now(),1,14,'0','0','1','입안의 달콤한 소확행 앨범입니다','입안의 달콤한 소확행!',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (27,now(),now(),1,15,'0','0','1','새로운 취미를 찾아 떠나는 소확행 앨범입니다','새로운 취미를 찾아 떠나는 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (28,now(),now(),1,16,'0','0','1','혼자서도 즐거운 소확행 앨범입니다','혼자서도 즐거워~',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (29,now(),now(),1,17,'0','0','1','작은 화면 속 소확행 앨범입니다','작은 화면 속 소확행',1);
INSERT INTO t_album (`album_id`,`created_at`,`modified_at`,`album_color_num`,`album_icon_num`,`is_blocked`,`is_deleted`,`is_official`,`description`,`name`,`creator_id`) VALUES (30,now(),now(),1,18,'0','0','1','아날로그 소확행 앨범입니다','아날로그 소확행',1);
