/*
-- Query: select *
from t_joy
where 1=1
LIMIT 0, 300

-- Date: 2024-03-18 23:22
*/
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (1,now(),now(),'좋아하는 배달음식 시키고 넷플릭스 보기',4,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (2,now(),now(),'한강 가서 물멍 때리기',1,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (3,now(),now(),'시원한 바람 맞으며 자전거 타기',18,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (4,now(),now(),'친구와 함께 인생네컷 찍기',12,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (5,now(),now(),'귀여운 동물 영상 보며 힐링하기',11,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (6,now(),now(),'방금 세탁한 빳빳한 새 이불 덮기',20,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (7,now(),now(),'빵집에서 갓 나온 빵 먹기',11,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (8,now(),now(),'반신욕하기',13,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (9,now(),now(),'퇴근길에 붕어빵 먹기',12,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (10,now(),now(),'좋아하는 노래 틀고 가만히 멍 때리기',23,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (11,now(),now(),'교보문고에서 책 구경하기',1,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (12,now(),now(),'칵테일 사랑 들으면서 산책하기',19,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (13,now(),now(),'좋아하는 카페 가서 시간 보내기',14,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (14,now(),now(),'길에서 만난 고양이 사진 찍기',9,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (15,now(),now(),'귀여운 해달 영상 보기',20,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (16,now(),now(),'용산역 계단에 앉아서 수다 떨기',4,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (17,now(),now(),'청계천에 앉아서 물멍 때리기',10,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (18,now(),now(),'맛있는 집밥 예쁘게 차려 먹기',20,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (19,now(),now(),'이불 덮고 차가운 공기 마시기',13,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (20,now(),now(),'키우고 있는 식물에 물 주기',5,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (21,now(),now(),'드라마 보면서 맥주 마시기',7,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (22,now(),now(),'귀여운 카카오톡 이모티콘 구매하기',24,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (23,now(),now(),'비 오는 날 침대에서 빗소리 듣기',17,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (24,now(),now(),'비 오는 날 장화 신고 물웅덩이 첨벙거리기',10,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (25,now(),now(),'좋아하는 비누로 샤워하기',7,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (26,now(),now(),'좋아하는 향수 뿌리고 나가기',15,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (27,now(),now(),'집 앞 공원에서 산책 나온 강아지랑 인사하기',13,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (28,now(),now(),'집 앞 놀이터에서 그네 타기',4,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (29,now(),now(),'밀린 웹툰 정주행하기',19,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (30,now(),now(),'따끈한 물에 족욕하기',19,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (31,now(),now(),'좋아하는 신발 신고 나가기',18,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (32,now(),now(),'장보고 냉장고 꽉꽉 채워넣기',16,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (33,now(),now(),'눈 오는 날 천사 만들기',6,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (34,now(),now(),'소파 위에서 뒹굴기',5,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (35,now(),now(),'샤워하고 좋아하는 바디로션 바르기',2,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (36,now(),now(),'초콜릿을 입안에서 살살 녹여 먹기',18,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (37,now(),now(),'깨끗하게 방 청소하기',24,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (38,now(),now(),'아침에 창문 열고 시원한 공기 마시기',6,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (39,now(),now(),'양손으로 따뜻한 차나 커피 마시기',22,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (40,now(),now(),'오래된 사진첩 뒤적이기',5,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (41,now(),now(),'이불 속에서 귤 까먹기',24,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (42,now(),now(),'시원한 얼음잔에 오렌지 주스 마시기',10,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (43,now(),now(),'다른 사람에게 칭찬해주기',10,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (44,now(),now(),'나를 위한 칭찬해주기',21,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (45,now(),now(),'따뜻한 물로 샤워하기',7,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (46,now(),now(),'카페에서 평소에 안 시키던 메뉴 도전하기',18,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (47,now(),now(),'유선 이어폰 감성 챙기기',14,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (48,now(),now(),'핸드폰 갤러리 보면서 추억 회상하기',7,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (49,now(),now(),'옷장 정리하기',10,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (50,now(),now(),'편지 쓰기',22,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (51,now(),now(),'좋아하는 카페 가서 읽고싶었던 책 읽기',20,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (52,now(),now(),'등산하기',18,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (53,now(),now(),'요트에서 좋아하는 노래 틀기',18,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (54,now(),now(),'쿠폰 모아서 공짜 음료 마시기',20,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (55,now(),now(),'이불빨래 후 포근한 이불 냄새 느끼기',9,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (56,now(),now(),'평소 먹고 싶었던 과자 구매해서 먹어보기',4,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (57,now(),now(),'하루 3끼 요리해서 만들어먹기',5,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (58,now(),now(),'베이킹해서 지인에게 선물해주기',15,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (59,now(),now(),'귀여운 스티커 사서 소지품 꾸미기',3,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (60,now(),now(),'일기쓰기',8,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (61,now(),now(),'아침에 일어나서 환기시키기',14,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (62,now(),now(),'아침 요가하기',1,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (63,now(),now(),'낮잠자기',11,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (64,now(),now(),'좋아하는 영화 보며 맥주 마시기',24,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (65,now(),now(),'혼자 기차 타고 바다 보고 오기',3,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (66,now(),now(),'지하철 타고 한강 건너면서 창밖 보기',7,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (67,now(),now(),'도시락 싸서 피크닉 가기',22,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (68,now(),now(),'새로운 운동 배워보기',19,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (69,now(),now(),'구름 사진 찍기',22,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (70,now(),now(),'핑크빛 노을 사진 찍기',16,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (71,now(),now(),'좋아하는 향 뿌리고 잠들기',15,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (72,now(),now(),'앨범 들어가서 작년 오늘의 추억 찾아보기',9,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (73,now(),now(),'노래 틀고 크게 감상하기',13,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (74,now(),now(),'전기장판 틀고 눕기',10,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (75,now(),now(),'슬픈 노래 들으면서 감정이입하기',8,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (76,now(),now(),'갤러리에서 눈에 들어오는 사진 따라그려보기',11,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (77,now(),now(),'카페에서 좋아하는 음료와 디저트 시키기',16,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (78,now(),now(),'좋아하는 니트 꺼내입기',18,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (79,now(),now(),'영화관에서 카라멜 팝콘 먹기',12,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (80,now(),now(),'비 올 때 장화신고 나가기',13,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (81,now(),now(),'퇴근하고 시원한 맥주 마시기',7,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (82,now(),now(),'제철과일 먹기',5,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (83,now(),now(),'어렸을 적 추억의 장소 방문하기',4,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (84,now(),now(),'밤하늘의 별 보기',21,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (85,now(),now(),'새로운 동네 가보기',20,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (86,now(),now(),'슬픈 영화 보고 펑펑 울며 감정 해소하기',17,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (87,now(),now(),'여행에서 찍었던 사진들 보며 기분 전환하기',3,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (88,now(),now(),'좋아하는 신나는 노래 듣기',15,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (89,now(),now(),'혼자 캔맥주 마시며 생각 정리하기',23,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (90,now(),now(),'동네 친구와 편의점에서 캔맥주 마시며 수다 떨기',14,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (91,now(),now(),'새콤달콤 종류별로 다 사먹기',5,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (92,now(),now(),'포장마차에서 어묵 먹기(국물도)',16,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (93,now(),now(),'귀여운 푸바오 영상 보기',15,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (94,now(),now(),'스키장 가서 캐롤 듣기',12,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (95,now(),now(),'친구들과 여행 계획 세우기',24,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (96,now(),now(),'초등학교 생활기록부 보기',12,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (97,now(),now(),'늦잠자기',11,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (98,now(),now(),'초중고 졸업사진 뒤적이기',14,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (99,now(),now(),'치킨 먹으면서 스포츠 경기 관람하기',1,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (100,now(),now(),'왓챠피디아에서 봤던 영화들 평점 매겨보기',21,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (101,now(),now(),'추억의 옛날 게임 해보기',18,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (102,now(),now(),'좋아하는 드라마 ost모음 듣기',11,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (103,now(),now(),'무한도전 레전드편 다시보기',24,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (104,now(),now(),'혼자서 길 안보고 여행지 돌아다녀보기',10,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (105,now(),now(),'계획없이 거리에서 버스킹 구경하기',8,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (106,now(),now(),'부모님께/연인에게/친구에게 사랑한다고 말하기',8,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (107,now(),now(),'친한 친구랑 전화해서 수다 떨기',20,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (108,now(),now(),'친구들과 왁자지껄 술 먹고 기분 좋게 취하기',19,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (109,now(),now(),'일어나자마자 이불 정리하기',11,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (110,now(),now(),'도서관 가서 읽고 싶은 책 고르기',6,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (111,now(),now(),'캠핑 가기',24,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (112,now(),now(),'잠자기 전 따뜻한 코코아 마시기',3,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (113,now(),now(),'잠옷 세트로 입기',24,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (114,now(),now(),'여행 브이로그 보면서 마음 속으로 여행 떠나기',11,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (115,now(),now(),'노트에 오늘 있었던 감사한 일 세 가지 적기',5,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (116,now(),now(),'서점에서 책 사기',10,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (117,now(),now(),'같이 서점 가서 서로에게 책 선물하기',6,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (118,now(),now(),'장바구니에 있던 물건 구매하기',14,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (119,now(),now(),'지난 생일에 받은 편지 다시 읽기',4,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (120,now(),now(),'친구들과의 단톡방 정주행하기',18,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (121,now(),now(),'비타오백 원샷하기',7,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (122,now(),now(),'여행 브이로그 보기',6,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (123,now(),now(),'반려동물 안고 온기 느끼기',18,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (124,now(),now(),'반려동물이 자는 모습 지켜보기',7,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (125,now(),now(),'가장 좋아하는 엄마표 음식 먹기',23,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (126,now(),now(),'가족과 함께 기념일 보내기',23,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (127,now(),now(),'가족들 모두 함께 모여 근사한 저녁 먹기',16,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (128,now(),now(),'가족과 함께 동네 산책하기',14,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (129,now(),now(),'가족들과 소소한 일상 대화하기',4,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (130,now(),now(),'부모님과 함께 영화관 가기',7,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (131,now(),now(),'여행지에서 엽서 사기',9,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (132,now(),now(),'음악 페스티벌 가기',9,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (133,now(),now(),'아침 운동으로 하루를 시작하기',6,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (134,now(),now(),'신나는 노래 들으며 거리 걷기',2,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (135,now(),now(),'좋아하는 노래 들으며 샤워하기',1,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (136,now(),now(),'즉흥여행 떠나기',6,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (137,now(),now(),'친구들과 함께 운동하기',4,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (138,now(),now(),'호텔 근처 거리 산책하기',3,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (139,now(),now(),'아기자기한 상점 구경하기',8,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (140,now(),now(),'눈부시게 맑은 파란 하늘보기',10,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (141,now(),now(),'여행지에서 인생샷 남기기',6,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (142,now(),now(),'호텔에서 반신욕 즐기기',9,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (143,now(),now(),'여행지에서 인생 맛집 만나기',15,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (144,now(),now(),'새로 나온 메뉴 배달시켜 먹기',17,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (145,now(),now(),'새로운 스타일의 옷 도전해보기',20,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (146,now(),now(),'빗소리 들으며 파전 먹기',7,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (147,now(),now(),'뜨끈한 국물요리 먹기',16,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (148,now(),now(),'우리 동네에만 있는 맛집 발견하기',6,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (149,now(),now(),'새로운 향 도전해보기',6,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (150,now(),now(),'가고 싶었던 여행지 맛집 찾기',19,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (151,now(),now(),'새로 나온 과자 먹어보기',21,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (152,now(),now(),'우산 쓰고 산책하기',20,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (153,now(),now(),'버스에서 비 오는 창밖 풍경 감상하기',8,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (154,now(),now(),'비 맞고 집 와서 뽀송하게 씻기',8,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (155,now(),now(),'동네 산책하며 구석구석 구경하기',3,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (156,now(),now(),'편의점 꿀조합 레시피 먹기',6,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (157,now(),now(),'여행지 쇼핑리스트 정리하기',22,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (158,now(),now(),'대전 성심당 다녀오기',8,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (159,now(),now(),'런던 베이글 뮤지엄 다녀오기',9,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (160,now(),now(),'군산 이성당 다녀오기',6,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (161,now(),now(),'연남동 만동제과 다녀오기',12,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (162,now(),now(),'낙성대 장블랑제리 다녀오기',22,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (163,now(),now(),'강릉 돌체테리아 다녀오기',20,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (164,now(),now(),'제주 빵귿 다녀오기',11,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (165,now(),now(),'집에서 직접 베이킹하기',10,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (166,now(),now(),'벚꽃 구경하기',8,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (167,now(),now(),'근교로 봄 나들이 떠나기',22,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (168,now(),now(),'봄 향기 물씬 풍기는 노래 듣기',9,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (169,now(),now(),'드라이브하며 따스한 햇살 느끼기',6,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (170,now(),now(),'노랗게 물든 봄 유채꽃 보기',23,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (171,now(),now(),'새출발하는 마음으로 봄 맞이하기',3,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (172,now(),now(),'스키장 가서 컵라면 먹기',22,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (173,now(),now(),'아침밥 챙겨먹기',12,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (174,now(),now(),'네잎클로버 발견하기',22,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (175,now(),now(),'젤리 사서 친구들에게 선물해주기',19,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (176,now(),now(),'아침에 좋아하는 차 한 잔 마시기',11,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (177,now(),now(),'아무도 밟지 않은 눈 밟아보기',9,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (178,now(),now(),'친구들과 함께 눈사람 만들기',1,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (179,now(),now(),'눈과 함께 사진 찍기',6,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (180,now(),now(),'눈싸움 하며 스트레스 해소하기',3,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (181,now(),now(),'귤 까먹으며 영화 보기',8,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (182,now(),now(),'아침에 개운하게 일어나기',10,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (183,now(),now(),'촉촉한 쿠키 먹기',20,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (184,now(),now(),'제철과일 빙수먹기',8,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (185,now(),now(),'스타벅스 최애 프라푸치노 먹기',6,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (186,now(),now(),'딸기 생크림 케이크 먹기',24,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (187,now(),now(),'꾸덕한 브라우니 먹기',8,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (188,now(),now(),'쫀득한 마카롱 먹기',19,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (189,now(),now(),'버터향 가득한 휘낭시에 먹기',1,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (190,now(),now(),'안 쓰는 중고제품 당근 거래하기',22,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (191,now(),now(),'플라잉 요가 도전해보기',16,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (192,now(),now(),'한강에서 보드 배워보기',2,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (193,now(),now(),'도자기 공방 체험하기',4,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (194,now(),now(),'혼자 1시간 넘게 산책하기',6,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (195,now(),now(),'가보고 싶던 식당 예약해서 혼밥하기',19,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (196,now(),now(),'혼자 영화관 가서 나쵸세트 먹으며 영화보기',24,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (197,now(),now(),'분위기 좋은 곳에서 혼술하기',15,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (198,now(),now(),'혼자 쇼핑하러 가기',5,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (199,now(),now(),'혼자 공원 벤치에 앉아서 여유 만끽하기',5,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (200,now(),now(),'나에게 꽃 선물하기',23,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (201,now(),now(),'혼자 도서관 가서 시간 보내기',18,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (202,now(),now(),'핸드폰 잠금화면 바꾸기',10,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (203,now(),now(),'핸드폰 배경화면 바꾸기',13,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (204,now(),now(),'SNS 프로필 새단장하기',1,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (205,now(),now(),'친구랑 영상통화하기',19,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (206,now(),now(),'새로운 유튜브 채널 발견하기',13,'OFFICIAL',1);


-- 0323 추가
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (207,now(),now(),'분위기 좋은 곳에서 브런치 먹기',1,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (208,now(),now(),'일상 속에서 영감 얻기',2,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (209,now(),now(),'가족들과 맛있는 거 먹기',3,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (210,now(),now(),'유행하는 요리 릴스 따라해보기',4,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (211,now(),now(),'요거트에 그래놀라 넣어서 먹기',5,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (212,now(),now(),'출퇴근길에 한강 보기',6,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (213,now(),now(),'지나다가다 마음에 드는 공간 발견하기',7,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (214,now(),now(),'사랑하는 사람들과 힐링음악 들으면서 놀기',8,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (215,now(),now(),'점심시간에 꽃구경 하기',9,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (216,now(),now(),'출근 전에 마실 거 챙겨서 출근하기',10,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (217,now(),now(),'등교길에 식빵 굽는 고양이 발견하기',11,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (218,now(),now(),'취침 10분 전에 오늘 하루를 되돌아보기',12,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (219,now(),now(),'부모님과 경치 좋은 곳에서 커피 한 잔 하기',13,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (220,now(),now(),'가족들과 삼겹살 파티하기',14,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (221,now(),now(),'맛있는 간식과 커피 한잔으로 느긋한 여유 즐기기',15,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (222,now(),now(),'캠핑장에서 불멍하기',16,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (223,now(),now(),'추운 날에 따뜻한 선물 교환식 하기',17,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (224,now(),now(),'출퇴근길에 취향에 맞는 노래 발견하기',18,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (225,now(),now(),'알람 없이 기상하며 늦잠 자기',19,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (226,now(),now(),'대학교 캠퍼스 산책하기',20,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (227,now(),now(),'좋아하는 카페에서 달달한 디저트 먹기',21,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (228,now(),now(),'월급날에 삼겹살에 소맥 한잔 하기',22,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (229,now(),now(),'반려동물과 집에서 뒹굴거리기',23,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (230,now(),now(),'반려동물과 산책하기',24,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (231,now(),now(),'맛있는 거 만들어 먹으며 하루종일 반려동물과 집에서 쉬기',23,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (232,now(),now(),'가족들이랑 외식하기',22,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (233,now(),now(),'출퇴근길에 맛있는 커피 한잔 들고 가기',21,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (234,now(),now(),'시원한 바다 보러 가기',20,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (235,now(),now(),'선물 받은 예쁜 컵에 스프 담아먹기',19,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (236,now(),now(),'취향에 꼭 맞는 플레이리스트 발견하기',18,'OFFICIAL',1);
INSERT INTO t_joy (`joy_id`,`created_at`,`modified_at`,`contents`,`joy_icon_num`,`joy_type`,`creator_id`) VALUES (237,now(),now(),'머리스타일 변화주기',17,'OFFICIAL',1);
